# Generated by Django 3.0.7 on 2020-06-16 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_error'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomReward',
        ),
        migrations.DeleteModel(
            name='CustomTask',
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
        migrations.DeleteModel(
            name='StandardTask',
        ),
        migrations.RenameField(
            model_name='userreward',
            old_name='name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='usertask',
            old_name='name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='userreward',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreward',
            name='last_updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userreward',
            name='status',
            field=models.CharField(choices=[('Earned', 'Earned'), ('Used', 'Used')], default='Earned', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreward',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertask',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertask',
            name='last_updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertask',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], max_length=64),
        ),
    ]
