# Generated by Django 3.0.7 on 2020-06-16 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200616_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreward',
            name='created_dt',
        ),
        migrations.RemoveField(
            model_name='userreward',
            name='last_updated_dt',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='created_dt',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='last_updated_dt',
        ),
    ]
