# Generated by Django 3.0.7 on 2020-06-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='points',
            new_name='total_points',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_points',
            field=models.IntegerField(default=0),
        ),
    ]
