# Generated by Django 3.0.7 on 2020-06-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20200619_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standardreward',
            old_name='name',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='userreward',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Used', 'Used')], max_length=64),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete')], max_length=64),
        ),
    ]
